### PR TITLE
Uploaded new logo and header cover

### PR DESCRIPTION
**Pull request by marcotroisi**

### CODE REVIEW

**Comment by jasonmadigan** [comment]
@marcotroisi don't suppose we've got higher-res copies of these available? The banner's a bit too low-res for anything other than a low-dpi mobile device.

**Comment by marcotroisi** [comment]
Dónal has asked his girl for higher-res versions, but we may have to wait a little while for those I think.

**Comment by jasonmadigan** [comment]
@marcotroisi did Donal ever get higher-res copies of these? Would be a nice addition!

**Comment by marcotroisi** [comment]
@jasonmadigan Dónal says the PDF (which I just uploaded) is high-res. Can you make something out of it?

**Comment by jasonmadigan** [comment]
Thanks @marcotroisi - see https://github.com/waterfordtechmeetup/waterfordtechmeetup.github.io/pull/6

**Pull request closed without merging**
